name: Ruby Gem

on: [pull_request]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 3.1.x
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.1.x

    - name: Update version file
      run: |
        echo "# frozen_string_literal: true

        module StructuraidCore
          VERSION = '0.1.2'
        end" > lib/structuraid_core/version.rb

    - uses: stefanzweifel/git-auto-commit-action@v4
      id: auto-commit-action
      with:
        skip_fetch: false
        commit_message: Update Version

    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
