name: Ruby Gem

on:
  release:
    types: [created]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 3.1.x
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.1.x

    - name: Update version file
      run: |
        echo "# frozen_string_literal: true

        module StructuraidCore
          VERSION = '${{ github.event.release.name }}'
        end" > lib/structuraid_core/version.rb

    - uses: stefanzweifel/git-auto-commit-action@v4
      id: auto-commit-action
      with:
        skip_fetch: false
        branch: main
        commit_message: Bump version to ${{ github.event.release.name }}

    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"

    - name: Update CHANGELOG
      uses: BobAnkh/auto-generate-changelog@v1
      with:
        REPO_NAME: 'PradaIng/structuraid-core'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PATH: 'CHANGELOG.md'
        COMMIT_MESSAGE: 'docs(CHANGELOG): update release notes'
        TYPE: 'feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements'
        BRANCH: 'main'
